### PR TITLE
Adding additional gross net salary calculator for Germany.

### PR DESCRIPTION
**Pull request by JonasHass**
I am running this site as a side project. I would appreciate it if you can add this to your useful link collection.

The gross-net salary calculator provides extra visualization for a better understanding of the net earning from the gross.

### CODE REVIEW

**Comment by trolologuy** [comment]
Hi, the @The-Wizzart, Thanks a lot for the PR! Your tool is awesome!
Is the tool open-source as well?
Need some help with translating it to french?

Some ideas for features:
- Add the option to calculate the gross based on the Netto
- Add some statistics as on [this french site](https://www.inegalites.fr/Salaire-etes-vous-riche-ou-pauvre)

**Comment by JonasHass** [comment]
Hi,

Thank you for the feedback and for accepting my pull request. 

1. A was thinking more about an API, or to encapsulate all the code into a single JavaScript file, this would make it easier to share.
2. I was looking for statistical data, but so far I was not able to find it for Germany.

Regards,
Rob

**Comment by trolologuy** [comment]
Hi Rob,

That would be cool!

Indeed it seems that the [data about wages](https://www.destatis.de/DE/Themen/Arbeit/Verdienste/Verdienste-Verdienstunterschiede/_inhalt.html#sprg475876) is tough to get (only spreadsheets etc) in Germany.

Kind regards,

Aloys

**Comment by JonasHass** [comment]
After some research finally I found some data and I visualised it as an [infographic](https://lohntastik.de/gns/gross-net-salary-calculator). 
Screenshot_20220718-213958_Chrome
 Still playing atound with the visualization:)

**Pull request merged**
